source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version.
# activesupport >= 7.2 requires Ruby >= 3.1.
ruby ">= 3.1"

# Exclude cocoapods versions with known build failures, and pin activesupport and
# concurrent-ruby to versions that patch known CVEs.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 7.2.3.1'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '>= 1.3.7'
