source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version.
# activesupport >= 7.2 requires Ruby >= 3.1.
ruby ">= 3.1"

# Cocoapods 1.15 introduced a bug which break the build. We will remove the upper
# bound in the template on Cocoapods with next React Native release.
gem 'cocoapods', '>= 1.13', '< 1.15'
# Pin activesupport to a version that patches known CVEs (>= 7.2.3.1).
gem 'activesupport', '>= 7.2.3.1'
